---
title: "Trust and Suitable Partners"
output: html_document
bibliography: SFI Report.bib
csl: apa.csl
---

  Researchers tend to co-author with colleges with similar research interests, while they predominately only cite those with differing interests [@ding_scientific_2011]. In this report we test the effect on network structure when various co-authorship propensities are altered. We start with a null model resembling Newman's physics co-authorship network [-@newman_coauthorship_2004], and alter <NAMES OF PARAMETERS> to see their effect on network formation.
  By altering the propensity of simulated researchers to match with co-authors of dissimilar interests, we can model the effect on the overall disconnectedness of a particular field, and the role individuals with differing distributions of expertise have on that structure. In doing so, we explore and make quantifiable the possible benefits of higher cross-expertise collaboration in the academic sphere.
  
# Literature Review

  Individuals have some agency regarding who they choose to associate with. While the utility of numerous weak ties has been explored [@granovetter_strength_1973], individuals will likely invest more heavily in some relationships over others. The selection of these close associates can be based on dyadic properties such as homophily [@mcpherson_birds_2001], necessity of resources [@lee_search_2014], or based on the potential associates' position in a broader social network [@jackson_strategic_1996; @buechel_dynamics_2008]. Regardless of reason, trusting relationships are understood to facilitate the transmission of resources between individuals [@coleman_social_1988].
  
  One example of this exists within the co-authorship networks of academia. Co-authorship networks differ structurally across disciplines [@newman_coauthorship_2004], thus the ability for social resources to flow across these networks will also differ. It has been shown that strong, direct ties between collaborators produces higher quality research, while working with colleges with similar research interests only influences research output [@gonzalez-brambila_impact_2013]. Further, betweenness centrality has shown to be a particularly good predictor of preferential treatment in a co-authorship network, as new entrants to the network approach these brokers when making their first connections [@abbasi_betweenness_2012]. We examine the effects on these metrics using the following model.

# Methods

  We specify the following parameters in out model: 
  the number of authors in the model ($\alpha$), 
  the number of iterations the model will run (t), 
  the threshold each agent uses to decide if another agent is similar enough in interests to co-author with,
  a decay parameter indicating how quickly agents will seek out agents who are less similar in interests,
  the maximum number of co-authors for any one agent,
  the max number of time an agent will try to match with someone before considering them undesirable,
  and what distribution is used to determine the talent level in our 5 sub-topics.


  We start with a number of isolates ($\alpha$), a set number of iterations (t), and !!!. At time = t, we randomly allow each node to initiate a connection with another node. If a node already has a partner, it is not eligible to be paired with. At time = t + 1, each of these connections are tested for affinity (trust). If both nodes are of the same sub-type, the connection is solidified as a trusting relationship. If nodes are of a different sub-type, the connection is dropped, and that tie is removed from the list of eligible ties in future iterations.

# Results
### Model 1
```{r Model 1, message=FALSE, warning=FALSE, include=FALSE}
source("src/jj_model_dynamic.r")
model1 = run_model()
```
#### Example Model with `r dim(model1$net_list_matrix[[1]])[1]` authors, `r length(model1$net_list)` iterations.
Click on the nodes to see their sub-topics!
`r model1$wid`

# Discussion

# Conclusion

  In creating this model, we showcase how small changes in the co-authorship behavior of researchers can greatly impact the structure of a field. Given that the type and quality of co-authorship ties have been shown to impact research quality and output, knowing what co-authorship behaviors to encourage can help enhance the scientific pursuit.

# Referances

---
nocite: | 
  @r_core_team_r:_2017, @handcock_statnet:_2003
...

