---
title: "Trust and Suitable Partners"
output: html_document
bibliography: SFI Report.bib
csl: biomed-central.csl
---

  Researchers tend to co-author with colleges with similar research interests, while they predominately only cite those with differing interests[@ding_scientific_2011]. In this report we test the effect on network structure when various co-authorship propensities are altered. We hypothesize that if co-authors !!!
  By altering the propensity of simulated researchers to match with co-authors of dissimilar interests, we can model the effect on the overall connectedness of a particular field, and the role individuals with differing distributions of expertise have one that structure. In doing so, we explore and make quantifiable the possible benefits of higher cross-expertise collaboration in the academic sphere.
  

# Literature Review

  Individuals have some agency regarding who they choose to associate with. While the utility of numerous weak ties has been explored[@granovetter_strength_1973], individuals will likely invest more heavily in some relationships over others. The selection of these close associates can be based on dyadic properties such as homophily[@mcpherson_birds_2001] or necessity[@lee_search_1969], or based on the potential associates' position in a broader social network [@jackson_strategic_1996, @buechel_closeness_2013]. Regardless of reason, trusting relationships are understood to facilitate the transmission of resources between individuals[@coleman_social_1988].
  One example of this exists within the co-authorship networks of academia. Co-authorship networks differ structurally across disciplines[@newman_coauthorship_2004], thus the ability for social resources to flow across these networks will also differ.

# Methods

  We start with a number of isolates ($\alpha$), a set number of iterations (t), and !!!. At time = t, we randomly allow each node to initiate a connection with another node. If a node already has a partner, it is not eligible to be paired with. At time = t + 1, each of these connections are tested for affinity (trust). If both nodes are of the same sub-type, the connection is solidified as a trusting relationship. If nodes are of a different sub-type, the connection is dropped, and that tie is removed from the list of eligible ties in future iterations.

# Results
### Model 1
`r source("../src/jj_model_dynamic.r")`
#### Example Model with `r num_authors` authors, `r iter` iterations.
`r wid`

# Discussion

# Conclusion

# Referances

---
nocite: | 
  @R, @statnet
...

